Repository sw19-tug/SPbPU2019, pull requests merged in 2019-12, with the labels that each got.

#94 [Hangman-7] Several Words (KM)
  Hangman/css/hangman.css
  Hangman/js/hangmanGame.js
Labels: Elephants, enhancement

#95 [FourRow-8] Added the ability to win the game (YH, GZ)
  FourInARow/css/stylesheet.css
  FourInARow/index.html
  FourInARow/scripts/Four in a row.js
Labels: Racoons, enhancement

#88 [Tron-2] changed movement logic (HI)
  Tron/TronJS.js
  Tron/TronStyle.css
  Tron/gameField.html
  Tron/index.html
Labels: Penguins, enhancement, help wanted

#96 [TicTacToe - 12] win the game (YI)
  TicTacToe/css/tictactoe.css
  TicTacToe/index.html
  TicTacToe/js/tictactoe.js
Labels: Elephants, enhancement

#100 [TicTacToe-20] drow game (in console) (YI)
  TicTacToe/js/tictactoe.js
Labels: Elephants, enhancement

#101 [Tron-6] added opponent (HI)
  Tron/TronJS.js
Labels: Penguins, enhancement

#99 [Hangman-12] draw hangman picture (KM)
  Hangman/css/hangman.css
  Hangman/index.html
  Hangman/js/hangmanGame.js
Labels: Elephants, enhancement

#105 [Minesweeper-4] Mines on Grid
  Minesweeper/MinesweeperJS.js
  Minesweeper/MinesweeperStyle.css
Labels: Penguins, enhancement

#106 [Tron-7] added win menu (HI,KI,DK)
  Tron/TronJS.js
  Tron/TronStyle.css
  Tron/gameField.html
Labels: Penguins

#107 [Invaders-0] create game field (KR, ER)
  SpaceInvaders/SpaceInvaders.rar
  SpaceInvaders/css/style.css
  SpaceInvaders/images/cannon.png
  SpaceInvaders/index.html
  SpaceInvaders/js/Game.js
Labels: Racoons, enhancement

#109 [Invaders-2] add the ability to move the cannon (ER)
  SpaceInvaders/SpaceInvaders.rar
  SpaceInvaders/index.html
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, documentation, enhancement

#108 [FourRow-6] Added ability to play in one move (YH)
  FourInARow/css/stylesheet.css
  FourInARow/index.html
  FourInARow/scripts/Four in a row.js
Labels: Racoons, enhancement

#110 [Invaders-3] add the ability to shoot from the cannon (ER)
  SpaceInvaders/css/style.css
  SpaceInvaders/images/cannon ball.png
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#111 [Invaders-26] add aliens (ER)
  SpaceInvaders/css/style.css
  SpaceInvaders/images/invader.png
  SpaceInvaders/js/Game.js
Labels: Racoons, enhancement

#102 [TicTacToe-8] add select sign in computer mode (DD)
  TicTacToe/css/tictactoe.css
  TicTacToe/index.html
  TicTacToe/js/tictactoe.js
Labels: Elephants, enhancement

#112 [Invaders-28] add ability to destroy aliens (ER)
  SpaceInvaders/index.html
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#115 [Invaders-5] add moving aliens from side to side (ER)
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#116 [Invaders-20] add aliens shooting (ER)
  SpaceInvaders/images/bullet.png
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#117 [Invaders-22.0] add lives decreasing (ER)
  SpaceInvaders/css/style.css
  SpaceInvaders/images/cannon gray.png
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#121 [TicTacToe-16] add random for signs (KM)
  TicTacToe/js/tictactoe.js
Labels: Elephants, enhancement

#128 Feature invaders 22
  SpaceInvaders/images/live.png
  SpaceInvaders/index.html
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#129 [Invaders-6] Add game over when aliens reach the bottom (VP)
  SpaceInvaders/css/style.css
  SpaceInvaders/index.html
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#131 [Invaders-32] End game on lifes finished (VM)
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#132 [Invaders-23] Add points (MV)
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#133 [Invaders-29] Add points for destroyed Aliens (VM)
  SpaceInvaders/css/style.css
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#137 [Invaders-24] Show number of points (VM)
  SpaceInvaders/css/style.css
  SpaceInvaders/images/live.png
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#139 [Invaders-33] Add end screen (ER)
  SpaceInvaders/css/style.css
  SpaceInvaders/index.html
  SpaceInvaders/js/Game.js
  SpaceInvaders/js/Main.js
Labels: Racoons, enhancement

#125 [Tron-9] added configure menu (HI)
  Tron/TronJS.js
  Tron/TronStyle.css
  Tron/index.html
Labels: Penguins

#141 [FourRow-13] Added instructions window (YH)
  FourInARow/css/stylesheet.css
  FourInARow/images/restart.svg
  FourInARow/index.html
  FourInARow/scripts/Four in a row.js
Labels: Racoons, enhancement

#142 [FourRow-3] Added ability to restart (YH)
  FourInARow/images/fab.gif
  FourInARow/index.html
  FourInARow/scripts/Four in a row.js
Labels: Racoons, enhancement

#148 [Minesweeper-4] Just refactoring (VR)
  Minesweeper/MinesweeperGameField.css
  Minesweeper/MinesweeperIndex.css
  Minesweeper/MinesweeperJS.js
  Minesweeper/gameField.html
  Minesweeper/index.html
Labels: Penguins, enhancement

#149 [Minesweeper-5] Adding number of mines nearby (AF)
  Minesweeper/MinesweeperJS.js
Labels: Penguins, enhancement

#150 [Minesweeper-6] Adding ability to loose the game and open all bombs (AF)
  Minesweeper/MinesweeperJS.js
Labels: Penguins, enhancement

#151 [Minesweeper-8] Adding ability to put flags on unopened sells (VR,AF)
  Minesweeper/MinesweeperJS.js
  Minesweeper/flag.png
Labels: Penguins, enhancement

#152 [Minesweeper-9] Adding ability to win the game by putting flags on se…
  Minesweeper/MinesweeperJS.js
Labels: Penguins, enhancement

#153 [Minesweeper-10] Adding ability to to have a flags left counter(KN)
  Minesweeper/MinesweeperGameField.css
  Minesweeper/MinesweeperJS.js
  Minesweeper/gameField.html
Labels: Penguins, enhancement

#154 [Minesweeper-11] Adding ability to configure grid(AF)
  Minesweeper/MinesweeperIndex.css
  Minesweeper/MinesweeperJS.js
  Minesweeper/index.html
Labels: Penguins, enhancement

#155 [Minesweeper-12] Adding result screen with statistics(VR)
  Minesweeper/MinesweeperGameField.css
  Minesweeper/MinesweeperIndex.css
  Minesweeper/MinesweeperJS.js
  Minesweeper/gameField.html
Labels: Penguins, enhancement

#144 [FourRow-5] Added color selection (GZ, YH)
  FourInARow/css/menu_style.css
  FourInARow/css/stylesheet.css
  FourInARow/game.html
  FourInARow/images/back.svg
  FourInARow/images/restart.svg
  FourInARow/images/window.png
  FourInARow/index.html
  FourInARow/scripts/Four in a row.js
  FourInARow/scripts/menu.js
Labels: Racoons, enhancement
