Repository sw19-tug/SPbPU2019, pull requests merged in 2019-11, with the labels that each got.

#72 [Tron-1] added startup menu (HI)
  Tron/TronJS.js
  Tron/TronStyle.css
  Tron/gameField.html
  Tron/img/menu-grid.jpg
  Tron/index.html
Labels: Penguins, enhancement

#73 Feature-hangman-1
  Hangman/css/hangman.css
  Hangman/font/FuturaPTBook.otf
  Hangman/img/background1.jpg
  Hangman/index.html
  Hangman/js/hangmanGame.js
Labels: enhancement

#74 [Hangman-2] add hangman image (DD)
  Hangman/css/hangman.css
  Hangman/index.html
Labels: enhancement

#76 Feature hangman 3
  Hangman/css/hangman.css
  Hangman/index.html
  Hangman/js/hangmanGame.js
Labels: Elephants, enhancement

#79 [TicTacToe-11] gamefield added (NK)
  TicTacToe/css/tictactoe.css
  TicTacToe/index.html
Labels: Elephants, enhancement

#91 [TicTacToe-13] add two-player mode (DD)
  TicTacToe/css/tictactoe.css
  TicTacToe/font/FuturaPTBook.otf
  TicTacToe/index.html
  TicTacToe/js/tictactoe.js
Labels: Elephants, enhancement

#92 [Hangman-10] big letters (LM)
  Hangman/css/hangman.css
  Hangman/index.html
  Hangman/js/hangmanGame.js
Labels: Elephants, enhancement
